# Generated by Django 5.1.4 on 2025-03-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link_to_payment',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
