# Generated by Django 5.1.4 on 2025-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disc", models.TextField(verbose_name="описание")),
            ],
            options={
                "verbose_name": "мотоцикл",
                "verbose_name_plural": "мотоциклы",
            },
        ),
    ]
