# Generated by Django 5.1.4 on 2025-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_lesson_desc_alter_lesson_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default=2, max_length=150, verbose_name='название'),
            preserve_default=False,
        ),
    ]
