# Generated by Django 5.1.4 on 2025-03-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='картинка'),
        ),
    ]
