# Generated by Django 5.1.4 on 2025-03-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_cours_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
