# Generated by Django 5.0.10 on 2025-04-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
